#!/usr/bin/env python

import argparse

from twisted_test import app


parser = argparse.ArgumentParser(description="Start web server")
parser.add_argument("port", type=int, default=8080, help="Listening port")

args = parser.parse_args()


app.start(args.port)
